<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ScreenRecall.Player</RootNamespace>
    <AssemblyName>ScreenRecall.Player</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\storage-lib\ScreenRecall.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ScreenRecall.Tests" />
  </ItemGroup>

</Project>
